<Project Sdk="Microsoft.NET.Sdk.IL">
  <PropertyGroup>
    <!-- Needed for CLRTestEnvironmentVariable. -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' != 'coreclr'">true</CLRTestTargetUnsupported>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <CLRTestEnvironmentVariable Include="DOTNET_DynamicMethodMaxUsedDescriptors" Value="2" />
  </ItemGroup>
</Project>
